# Guardar em /etc/fail2ban/jail.d/dados-api.conf
[dados-api-auth]
enabled  = true
filter   = dados-api-auth
port     = http,https
logpath  = /var/log/nginx/dados-api.access.log
maxretry = 8
findtime = 10m
bantime  = 1h
ignoreip = 127.0.0.1/8 ::1 192.168.68.0/24
